[workspace]
resolver = "2"
members = [
    "load_csv",
    "load_csv_with_schema",
    "load_csv_lazy",
]

[workspace.dependencies]
anyhow = "1"
polars = "0.33.2"

[profile.release]
codegen-units = 1
lto = true
