[workspace]
resolver = "2"
members = [
    "schemata",
    "load_csv",
    "load_csv_with_schema",
    "load_csv_lazy",
    "inner_join_and_filter",
]

[workspace.dependencies]
anyhow = "1"
chrono = "0.4"
chrono-tz = "0.8"
polars = "0.33.2"

[profile.release]
codegen-units = 1
lto = true
