[package]
name = "load_csv_with_schema"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true

[dependencies.polars]
workspace = true
features = [
    "csv",
    "lazy",
    "temporal",
    "dtype-datetime",
]
